### ISSUE TITLE
When do you plan to release this code?

### ISSUE THREAD

**Issue by AmingWu** [SamWilso/SAFE_Official#1]
Dear Authors,

The performance of your work is impressive. When do you plan to release this code?

**Comment by SamWilso** [comment]
Thanks for your interest in our work! 

The code is delayed by a few weeks due to timing conflicts with my wedding and honeymoon. I hope you can understand my prioritisation of the latter items. 

Late October is the best estimate I can give. I apologise for the delay.

**Comment by AmingWu** [comment]
OK. If you release the code, could you tell me? Thank you.

**Comment by SamWilso** [comment]
Hi @AmingWu, terribly sorry for the delays. The code is now uploaded to reproduce the results from SAFE. If any troubles are encountered, please raise an issue and I'll be happy to assist.
