### ISSUE TITLE
ModuleNotFoundError: No module named 'modeling'

### ISSUE THREAD

**Issue by BUAACY** [SamWilso/SAFE_Official#2]
File "/root/SAFE/SAFE_Official-main/SAFE_interface.py", line 16, in <module>
    from core.setup import setup_arg_parser
  File "/root/SAFE/SAFE_Official-main/core/setup.py", line 23, in <module>
    from modeling.probabilistic_retinanet import ProbabilisticRetinaNet
ModuleNotFoundError: No module named 'modeling'

**Comment by BUAACY** [comment]
AttributeError: module 'offline_evaluation.compute_average_precision' has no attribute 'main_fileless'

**Comment by SamWilso** [comment]
Hi, thank you for pointing out this error. Some of the folders containing the modified VOS benchmark were missed in moving from my development machine to the git repo. The latest commit includes the 3 missing folders: modeling, inference and offline_evaluation. 

Please let me know if you continue to experience issues.
