### ISSUE TITLE
Argument for Evaluation part

### ISSUE THREAD

**Issue by DuongVanKhoa0811** [SamWilso/SAFE_Official#4]
The values for command line argument '--task' in the Evaluation is 'eval' or 'train'? Could you confirm, since the current value for '--task' is 'train', and I think that should be 'eval'. Thank you.

**Comment by SamWilso** [comment]
Thank you for raising this issue. Yes, you are absolutely correct. Use 'eval' to run evaluation with SAFE. I've fixed the README to reflect this.
